"""Add AnalysisJob table for async queue

Revision ID: 8562ca56853a
Revises: eb58b88f066e
Create Date: 2026-02-15 21:59:52.610523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8562ca56853a'
down_revision: Union[str, Sequence[str], None] = 'eb58b88f066e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('script_id', sa.String(length=36), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'PROCESSING', 'COMPLETED', 'FAILED', name='jobstatus'), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('genre', sa.String(length=100), nullable=True),
    sa.Column('comps', sa.JSON(), nullable=True),
    sa.Column('analysis_depth', sa.String(length=20), nullable=False),
    sa.Column('script_text_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['coverage_reports.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['script_id'], ['script_metadata.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_jobs_script_id'), 'analysis_jobs', ['script_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analysis_jobs_script_id'), table_name='analysis_jobs')
    op.drop_table('analysis_jobs')
    # ### end Alembic commands ###
