"""Initial migration

Revision ID: eb58b88f066e
Revises: 
Create Date: 2026-02-15 16:58:47.557673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb58b88f066e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('script_metadata',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('filename_hash', sa.String(length=64), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('format', sa.Enum('PDF', 'FDX', name='scriptformat'), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('author', sa.String(length=500), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_script_metadata_file_hash'), 'script_metadata', ['file_hash'], unique=False)
    op.create_index(op.f('ix_script_metadata_user_id'), 'script_metadata', ['user_id'], unique=False)
    op.create_table('coverage_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('script_id', sa.String(length=36), nullable=False),
    sa.Column('genre', sa.String(length=100), nullable=True),
    sa.Column('comps', sa.JSON(), nullable=True),
    sa.Column('analysis_depth', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('PROCESSING', 'COMPLETED', 'FAILED', name='reportstatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('subscores', sa.JSON(), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=True),
    sa.Column('recommendation', sa.Enum('PASS', 'CONSIDER', 'RECOMMEND', name='recommendation'), nullable=True),
    sa.Column('logline', sa.Text(), nullable=True),
    sa.Column('synopsis', sa.Text(), nullable=True),
    sa.Column('overall_comments', sa.Text(), nullable=True),
    sa.Column('strengths', sa.JSON(), nullable=False),
    sa.Column('weaknesses', sa.JSON(), nullable=False),
    sa.Column('character_notes', sa.Text(), nullable=True),
    sa.Column('structure_analysis', sa.Text(), nullable=True),
    sa.Column('market_positioning', sa.Text(), nullable=True),
    sa.Column('evidence_quotes', sa.JSON(), nullable=False),
    sa.Column('model_used', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['script_id'], ['script_metadata.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coverage_reports_script_id'), 'coverage_reports', ['script_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coverage_reports_script_id'), table_name='coverage_reports')
    op.drop_table('coverage_reports')
    op.drop_index(op.f('ix_script_metadata_user_id'), table_name='script_metadata')
    op.drop_index(op.f('ix_script_metadata_file_hash'), table_name='script_metadata')
    op.drop_table('script_metadata')
    # ### end Alembic commands ###
